server.port := 8088
server.username := ""
server.groupname := ""

$SERVER["socket"] == ":91" {
    cgi.assign += ( ".php" => "/opt/bin/php-cgi" )
    static-file.exclude-extensions += (".php")
    setenv.set-environment = ( "PATH" => "/opt/sbin:/opt/bin:/opt/usr/sbin:/opt/usr/bin:/usr/sbin:/usr/bin:/sbin:/bin" )
    index-file.names = ( "index.html" )
    server.error-handler-404 = "/xkeen/index.html"
    url.rewrite-once = ( "^/(.*)" => "/xkeen/$1" )
}
