#!/bin/sh

/etc/init.d/lighttpd restart

ip_addr=$(ip -f inet addr show dev br-lan 2>/dev/null | grep inet | sed -n 's/.*inet \([0-9.]\+\).*/\1/p')
echo "XKeen Web Interface installed: http://$ip_addr:91"

exit 0
